version: '3.3'

services:
  db:
    image: postgres
    restart: on-failure
#    environment:
#      POSTGRES_PASSWORD: mysecretpassword
#      POSTGRES_USER: postgres
#      POSTGRES_DB: mydatabase
    env_file:
      - .docker.env
#    volumes:
#      - db_data:/var/lib/postgresql/data
    container_name: db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog:
    image: catalog-svc
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: catalog-svc
    restart: on-failure
    env_file:
      - .docker.env
    depends_on:
      - db
    ports:
      - "8080:8080"
    entrypoint: "yes"
#    command: "serve"