// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Conty111/CarsCatalog/internal/app/dependencies"
	"github.com/Conty111/CarsCatalog/internal/app/initializers"
	"github.com/Conty111/CarsCatalog/internal/configs"
	"github.com/Conty111/CarsCatalog/internal/external_api"
	"github.com/Conty111/CarsCatalog/internal/repositories"
	"github.com/Conty111/CarsCatalog/internal/services"
)

// Injectors from wire.go:

func BuildApplication() (*Application, error) {
	configuration := configs.GetConfig()
	httpServerConfig := configuration.HTTPServer
	info := initializers.InitializeBuildInfo()
	db := initializers.InitializeDatabase(configuration)
	carRepository := repositories.NewCarRepository(db)
	client := external_api.NewClient(configuration)
	userRepository := repositories.NewUserRepository(db)
	service := services.NewCarService(carRepository, client, userRepository)
	container := &dependencies.Container{
		BuildInfo:  info,
		Config:     configuration,
		CarService: service,
	}
	engine := initializers.InitializeRouter(container)
	server, err := initializers.InitializeHTTPServer(httpServerConfig, engine)
	if err != nil {
		return nil, err
	}
	application := &Application{
		httpServer: server,
		db:         db,
		Container:  container,
	}
	return application, nil
}
