// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Conty111/CarsCatalog/internal/app/dependencies"
	"github.com/Conty111/CarsCatalog/internal/app/initializers"
	"github.com/Conty111/CarsCatalog/internal/configs"
)

// Injectors from wire.go:

func BuildApplication() (*Application, error) {
	info := initializers.InitializeBuildInfo()
	configuration := configs.GetConfig()
	container := &dependencies.Container{
		BuildInfo: info,
		Config:    configuration,
	}
	engine := initializers.InitializeRouter(container)
	httpServerConfig := initializers.InitializeHTTPServerConfig(engine)
	server, err := initializers.InitializeHTTPServer(httpServerConfig)
	if err != nil {
		return nil, err
	}
	db := initializers.InitializeDatabase(container)
	application := &Application{
		httpServer: server,
		db:         db,
		Container:  container,
	}
	return application, nil
}
